export const getFaqBoard = () => {
  return {
    id: "lybx5vzpmpim40z2ogc",
    name: "FAQ",
    children: [
      {
        id: "lybx68j4xcwn2k1jv2",
        name: "What is the purpose of this tool?",
        children: [
          {
            id: "lybx6g7vut8etovhsx",
            name: "Tracking and organizing information about any topic, using notes that are organized into trees",
            children: [],
            type: "ItemNode",
            boardId: "lybx5vzpmpim40z2ogc",
            parentId: "lybx68j4xcwn2k1jv2",
            highlightedNode: null,
          },
        ],
        type: "ItemNode",
        boardId: "lybx5vzpmpim40z2ogc",
        parentId: "lybx5vzpmpim40z2ogc",
        highlightedNode: null,
      },
      {
        id: "lybx71uq0fr7ls17lxct",
        name: "What does the basic workflow look like?",
        children: [
          {
            id: "lybx7zoqwzg5wxviyio",
            name: "1. Write down notes from any source in the bottom section of the UI",
            children: [],
            type: "ItemNode",
            boardId: "lybx5vzpmpim40z2ogc",
            parentId: "lybx71uq0fr7ls17lxct",
            highlightedNode: null,
          },
          {
            id: "lybx8808muz7mn9xhgf",
            name: '2. These notes are "loose", they don\'t belong to any board',
            children: [],
            type: "ItemNode",
            boardId: "lybx5vzpmpim40z2ogc",
            parentId: "lybx71uq0fr7ls17lxct",
            highlightedNode: null,
          },
          {
            id: "lybx8jq51dya9njsmpm",
            name: '3. Create a board by clicking the "New board" button in the left sidebar',
            children: [],
            type: "ItemNode",
            boardId: "lybx5vzpmpim40z2ogc",
            parentId: "lybx71uq0fr7ls17lxct",
            highlightedNode: null,
          },
          {
            id: "lybx8u9ifk1j6ngujaw",
            name: "4. Select the board by clicking on it, and drag your loose notes onto the board",
            children: [],
            type: "ItemNode",
            boardId: "lybx5vzpmpim40z2ogc",
            parentId: "lybx71uq0fr7ls17lxct",
            highlightedNode: null,
          },
        ],
        type: "ItemNode",
        boardId: "lybx5vzpmpim40z2ogc",
        parentId: "lybx5vzpmpim40z2ogc",
        highlightedNode: null,
      },
      {
        id: "lybx9h86qjlsbmrwnm",
        name: "What are some convenience features?",
        children: [
          {
            id: "lybxa69qda1etakxtch",
            name: "Clicking a note on a board opens a prompt to connect a new note to the one you clicked",
            children: [
              {
                id: "lybxna6ac8ihsq2v37h",
                name: "Try clicking this note...",
                children: [],
                type: "ItemNode",
                boardId: "lybx5vzpmpim40z2ogc",
                parentId: "lybxa69qda1etakxtch",
                highlightedNode: null,
              },
            ],
            type: "ItemNode",
            boardId: "lybx5vzpmpim40z2ogc",
            parentId: "lybx9h86qjlsbmrwnm",
            highlightedNode: null,
          },
          {
            id: "lybxaiw0cvdb2cj9nad",
            name: "Notes can be dragged around",
            children: [
              {
                id: "lybxazr1xx3d3jcej5",
                name: "Dropping one note on another note on the board will place the first note to the position of the second note",
                children: [
                  {
                    id: "lybxb882ud6tue6qxoo",
                    name: "Try arranging the letters:",
                    children: [
                      {
                        id: "lybxbc0xdhw2fwttvzb",
                        name: "B",
                        children: [],
                        type: "ItemNode",
                        boardId: "lybx5vzpmpim40z2ogc",
                        parentId: "lybxbay7jf1hjkg025",
                        highlightedNode: null,
                      },
                      {
                        id: "lybxbdzk81mntalrg75",
                        name: "D",
                        children: [],
                        type: "ItemNode",
                        boardId: "lybx5vzpmpim40z2ogc",
                        parentId: "lybxbcw751z3zo018g6",
                        highlightedNode: null,
                      },
                      {
                        id: "lybxbay7jf1hjkg025",
                        name: "A",
                        children: [],
                        type: "ItemNode",
                        boardId: "lybx5vzpmpim40z2ogc",
                        parentId: "lybxbcw751z3zo018g6",
                        highlightedNode: null,
                      },
                      {
                        id: "lybxbcw751z3zo018g6",
                        name: "C",
                        children: [],
                        type: "ItemNode",
                        boardId: "lybx5vzpmpim40z2ogc",
                        parentId: "lybxbay7jf1hjkg025",
                        highlightedNode: null,
                      },
                    ],
                    type: "ItemNode",
                    boardId: "lybx5vzpmpim40z2ogc",
                    parentId: "lybxazr1xx3d3jcej5",
                    highlightedNode: null,
                  },
                ],
                type: "ItemNode",
                boardId: "lybx5vzpmpim40z2ogc",
                parentId: "lybxaiw0cvdb2cj9nad",
                highlightedNode: null,
              },
              {
                id: "lybxdnjcpt4j9jny53p",
                name: "You can also drag a note, along with its subtree into the bottom section. The subtree will be preserved, and you can drag it from the bottom section to another board",
                children: [],
                type: "ItemNode",
                boardId: "lybx5vzpmpim40z2ogc",
                parentId: "lybxaiw0cvdb2cj9nad",
                highlightedNode: null,
              },
              {
                id: "lybxqin2gdaf5tmesi",
                name: "Dragging a note from the bottom section onto a note on the board, will connect the two notes",
                children: [],
                type: "ItemNode",
                boardId: "lybx5vzpmpim40z2ogc",
                parentId: "lybxaiw0cvdb2cj9nad",
                highlightedNode: null,
              },
            ],
            type: "ItemNode",
            boardId: "lybx5vzpmpim40z2ogc",
            parentId: "lybx9h86qjlsbmrwnm",
            highlightedNode: null,
          },
          {
            id: "lybxgl6qfzn211w30fu",
            name: "Questions that are written in notes are collected in the right sidebar",
            children: [
              {
                id: "lybxhht1who9ddgukw",
                name: 'If a question note is connected to an "answer" note, the question will no longer appear in the sidebar. An answer note can be created by prefixing the note with "A: "',
                children: [
                  {
                    id: "lybxhoe2mrl3ge62g9",
                    name: "Example question?",
                    children: [
                      {
                        id: "lybxi0xcudacf22qnxj",
                        name: "Some context...",
                        children: [],
                        type: "ItemNode",
                        boardId: "lybx5vzpmpim40z2ogc",
                        parentId: "lybxhoe2mrl3ge62g9",
                        highlightedNode: null,
                      },
                      {
                        id: "lybxi3qldishfob78p",
                        name: "Some more context....",
                        children: [],
                        type: "ItemNode",
                        boardId: "lybx5vzpmpim40z2ogc",
                        parentId: "lybxhoe2mrl3ge62g9",
                        highlightedNode: null,
                      },
                      {
                        id: "lybxiq804oh48duh8xr",
                        name: "A: Answer.",
                        children: [],
                        type: "ItemNode",
                        boardId: "lybx5vzpmpim40z2ogc",
                        parentId: "lybxhoe2mrl3ge62g9",
                        highlightedNode: null,
                      },
                    ],
                    type: "ItemNode",
                    boardId: "lybx5vzpmpim40z2ogc",
                    parentId: "lybxhht1who9ddgukw",
                    highlightedNode: null,
                  },
                ],
                type: "ItemNode",
                boardId: "lybx5vzpmpim40z2ogc",
                parentId: "lybxgl6qfzn211w30fu",
                highlightedNode: null,
              },
            ],
            type: "ItemNode",
            boardId: "lybx5vzpmpim40z2ogc",
            parentId: "lybx9h86qjlsbmrwnm",
            highlightedNode: null,
          },
          {
            id: "lybxm4gawt0ma7ccd0f",
            name: "Export a board by clicking the 'E' button next to it in the left sidebar",
            children: [
              {
                id: "lybxmestal1j3w1jlgr",
                name: "This will copy the board data into your clipboard",
                children: [
                  {
                    id: "lybxmrvgg5qo3yx879",
                    name: "You can paste this data when importing a board",
                    children: [],
                    type: "ItemNode",
                    boardId: "lybx5vzpmpim40z2ogc",
                    parentId: "lybxmestal1j3w1jlgr",
                    highlightedNode: null,
                  },
                ],
                type: "ItemNode",
                boardId: "lybx5vzpmpim40z2ogc",
                parentId: "lybxm4gawt0ma7ccd0f",
                highlightedNode: null,
              },
            ],
            type: "ItemNode",
            boardId: "lybx5vzpmpim40z2ogc",
            parentId: "lybx9h86qjlsbmrwnm",
            highlightedNode: null,
          },
        ],
        type: "ItemNode",
        boardId: "lybx5vzpmpim40z2ogc",
        parentId: "lybx5vzpmpim40z2ogc",
        highlightedNode: null,
      },
    ],
    type: "ItemNode",
    boardId: null,
    parentId: null,
    highlightedNode: null,
  };
};
